### ISSUE TITLE
up/down 3d stereoscopic 360 video support?

### ISSUE THREAD

**Issue by mrbemani** [ejeinc/VRVideoPlayer#3]
can this play up/down 3d stereoscopic 360 video?

**Comment by niusounds** [comment]
To play up/down 3d stereoscopic 360 video, add this line into `VideoPlayerApp.java` at 133 line.

```java
video.getRenderData().getMaterial().setStereoMode(Material.StereoMode.TOP_BOTTOM);
```

If video is left/right stereo, change to this

```java
video.getRenderData().getMaterial().setStereoMode(Material.StereoMode.LEFT_RIGHT);
```

**Comment by mrbemani** [comment]
thanks alot! that really helped!
